services:
  - type: web
    name: multitube
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SITE_URL
        value: https://multitube.onrender.com
      - key: CORS_ORIGIN
        value: "*"